MvcCecep/Controllers/EmpresaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MvcCecep;
using System.Web.Security;

namespace MvcCecep.Controllers
{
    public class EmpresaController : Controller
    {
        private CecepEntities db = new CecepEntities();

        // GET: Empresa
        public ActionResult Index()
        {
            var ccempresa = db.ccempresa.Include(c => c.ccarea);
            return View(ccempresa.ToList());
        }

        // GET: Empresa/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ccempresa ccempresa = db.ccempresa.Find(id);
            if (ccempresa == null)
            {
                return HttpNotFound();
            }
            return View(ccempresa);
        }

        // GET: Empresa/Create
        public ActionResult Create()
        {
            ViewBag.ccareaid = new SelectList(db.ccarea, "ccareaid", "codigo");
            return View();
        }

        // POST: Empresa/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ccempresa ccempresa, string contra2)
        {
            ccempresa.fechacreacion = DateTime.Now;


            if (ccempresa.contraseña != contra2)
            {
                ModelState.AddModelError("contraseña", "Las contraseñas no coinciden por favor verifique");
            }

            try
            {
                var emp = db.ccempresa.Where(x => x.loggin == ccempresa.loggin);

                if (emp.Count() > 0)
                {
                    ModelState.AddModelError("loggin", "Este usuario ya esta en uso");
                }

            }
            catch { }

            try
            {
                var emp = db.ccempresa.Where(x => x.nit == ccempresa.nit);
                if (emp.Count() > 0)
                {
                    ModelState.AddModelError("nit", "Este Nit ya ha sido registrado con anterioridad, por favor verifique");
                }
            }
            catch { }


            if (ModelState.IsValid)
            {
                db.ccempresa.Add(ccempresa);
                db.SaveChanges();

                return RedirectToAction("Login", "Account");
            }


            ViewBag.ccareaid = new SelectList(db.ccarea, "ccareaid", "codigo", ccempresa.ccareaid);


            return View(ccempresa);
        }

        // GET: Empresa/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ccempresa ccempresa = db.ccempresa.Find(id);
            if (ccempresa == null)
            {
                return HttpNotFound();
            }
            ViewBag.ccareaid = new SelectList(db.ccarea, "ccareaid", "codigo", ccempresa.ccareaid);
            return View(ccempresa);
        }

        // POST: Empresa/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ccempresaid,nit,dv,descripcion,direccion,telefono,celular,contactnombre,contacttelefono,contactcelular,loggin,contraseña,fechafundacion,ccareaid,fechacreacion")] ccempresa ccempresa)
        {
            if (ModelState.IsValid)
            {
                db.Entry(ccempresa).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ccareaid = new SelectList(db.ccarea, "ccareaid", "codigo", ccempresa.ccareaid);
            return View(ccempresa);
        }

        // GET: Empresa/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ccempresa ccempresa = db.ccempresa.Find(id);
            if (ccempresa == null)
            {
                return HttpNotFound();
            }
            return View(ccempresa);
        }

        // POST: Empresa/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ccempresa ccempresa = db.ccempresa.Find(id);
            db.ccempresa.Remove(ccempresa);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MvcCecep/Controllers/EventoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.Data.Entity;


namespace MvcCecep.Controllers
{
    public class EventoController : Controller
    {
        private CecepEntities db = new CecepEntities();

        // GET: Evento
        public ActionResult Index()
        {
            var modelo = db.ccevento.ToList();

            return View(modelo);
        }

        // GET: Evento/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Evento/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ccevento ccevento)
        {
            try
            {
                db.ccevento.Add(ccevento);
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View(ccevento);
            }
        }

        // GET: Evento/Edit/5
        public ActionResult Edit(int id)
        {
            var modelo = db.ccevento.Find(id);

            return View(modelo);
        }

        // POST: Evento/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ccevento ccevento)
        {
            try
            {
                db.Entry(ccevento).State = EntityState.Modified;
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View(ccevento);
            }
        }

        // GET: Evento/Delete/5
        public ActionResult Delete(int id)
        {
            var modelo = db.ccevento.Find(id);

            return View(modelo);
        }

        // POST: Evento/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var ccevento = db.ccevento.Find(id);
            try
            {
                db.ccevento.Remove(ccevento);
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View(ccevento);
            }
        }
    }
}

MvcCecep/Controllers/NoticiaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using System.Data;


namespace MvcCecep.Controllers
{
    public class NoticiaController : Controller
    {
        private CecepEntities db = new CecepEntities();

        // GET: Noticia
        public ActionResult Index()
        {
            var modelo = db.ccnoticia.ToList();

            return View(modelo);
        }       

        // GET: Noticia/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Noticia/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ccnoticia ccnoticia)
        {
            try
            {
                db.ccnoticia.Add(ccnoticia);
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View(ccnoticia);
            }
        }

        // GET: Noticia/Edit/5
        public ActionResult Edit(int id)
        {
            var modelo = db.ccnoticia.Find(id);

            return View(modelo);
        }

        // POST: Noticia/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ccnoticia ccnoticia)
        {
            try
            {
                db.Entry(ccnoticia).State = EntityState.Modified;
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View(ccnoticia);
            }
        }

        // GET: Noticia/Delete/5
        public ActionResult Delete(int id)
        {
            var modelo = db.ccnoticia.Find(id);

            return View(modelo);
        }

        // POST: Noticia/Delete/5
        [HttpPost,ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var ccnoticia = db.ccnoticia.Find(id);
            try
            {
                db.ccnoticia.Remove(ccnoticia);
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View(ccnoticia);
            }
        }
    }
}

MvcCecep/Controllers/ServicioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using System.Data;

namespace MvcCecep.Controllers
{
    public class ServicioController : Controller
    {
        private CecepEntities db = new CecepEntities();
        // GET: Servicio
        public ActionResult Index()
        {
            var modelo = db.cctiposerv.ToList();

            return View(modelo);
        }

        // GET: Servicio/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Servicio/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Servicio/Create
        [HttpPost]
        public ActionResult Create(cctiposerv cctiposerv)
        {
            if (ModelState.IsValid)
            {
                db.cctiposerv.Add(cctiposerv);
                db.SaveChanges();

                return RedirectToAction("Edit", new { id = cctiposerv.cctiposervid });
            }

            return View(cctiposerv);
        }

        // GET: Servicio/Edit/5
        public ActionResult Edit(int id)
        {
            var modelo = db.cctiposerv.Find(id);

            return View(modelo);
        }

        // POST: Servicio/Edit/5
        [HttpPost]
        public ActionResult Edit(cctiposerv cctiposerv)
        {

            if (ModelState.IsValid)
            {
                db.Entry(cctiposerv).State = EntityState.Modified;
                db.SaveChanges();

                return RedirectToAction("Index");
            }

            return View();

        }

        // GET: Servicio/Delete/5
        public ActionResult Delete(int id)
        {
            var modelo = db.cctiposerv.Find(id);

            return View(modelo);
        }

        // POST: Servicio/Delete/5
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            var modelo = db.cctiposerv.Find(id);

            try
            {
                db.cctiposerv.Remove(modelo);
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }


        #region Detalle

        public ActionResult CreateDetalle(int id)
        {
            cctiposervdet cctiposervdet = new cctiposervdet();
            cctiposervdet.cctiposervid = id;

            ViewBag.PossibleCategorias = db.cctiposervcat.ToList();


            return View(cctiposervdet);
        }

        [HttpPost]
        public ActionResult CreateDetalle(cctiposervdet cctiposervdet)
        {
            if (ModelState.IsValid)
            {
                db.cctiposervdet.Add(cctiposervdet);
                db.SaveChanges();

                return RedirectToAction("Edit", new { id = cctiposervdet.cctiposervid });
            }

            ViewBag.PossibleCategorias = db.cctiposervcat.ToList();

            return View(cctiposervdet);
        }

        public ActionResult EditDetalle(int id)
        {
            cctiposervdet cctiposervdet = db.cctiposervdet.Find(id);

           
            ViewBag.PossibleCategorias = db.cctiposervcat.ToList();

            return View(cctiposervdet);
        }

        [HttpPost]
        public ActionResult EditDetalle(cctiposervdet cctiposervdet)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cctiposervdet).State = EntityState.Modified;
                db.SaveChanges();

                return RedirectToAction("Edit", new { id = cctiposervdet.cctiposervid });
            }

            ViewBag.PossibleCategorias = db.cctiposervcat.ToList();

            return View(cctiposervdet);
        }

        #endregion



    }
}

MvcCecep/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title - Cecep</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />


    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-2.1.4.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>
</head>
<body>
    <header>
        @*<nav class="navbar navbar-default">
                <div class="container-fluid">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <div class="navbar-header">

                        <a href="~/Home/Index"><img src="~/Images/logo-cecep.jpg" style="width:150px;" /></a>
                    </div>

                    <div class="collapse navbar-collapse">
                        <ul class="nav navbar-nav">
                            <li>@Html.ActionLink("Empresas", "Index", "Empresa")</li>
                            <li>@Html.ActionLink("Peticiones", "Index", "Peticion")</li>

                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a href="#">Action</a></li>
                                    <li><a href="#">Another action</a></li>
                                    <li><a href="#">Something else here</a></li>
                                    <li role="separator" class="divider"></li>
                                    <li class="dropdown-header">Nav header</li>
                                    <li><a href="#">Separated link</a></li>
                                    <li><a href="#">One more separated link</a></li>
                                </ul>
                            </li>

                        </ul>

                        <ul class="nav navbar-nav navbar-right">
                            @Html.Partial("_LoginPartial")
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </div><!-- /.container-fluid -->
            </nav>*@

        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <a class="navbar-brand" href="#">Brand</a>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">

                        <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                        <li>@Html.ActionLink("¿Quienes somos?", "About", "Home")</li>

                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Servicios <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li>
                                    @Html.ActionLink("Registro de empresas", "Create", "Empresa")
                                </li>
                                <li>
                                    @Html.ActionLink("Administracion de empresas", "Index", "Empresa")
                                </li>
                                <li>@Html.ActionLink("Peticiones", "Index", "Peticion")</li>




                                <li>@Html.Partial("_LoginPartial")</li>
                            </ul>
                        </li>

                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Eventos<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li>
                                    @Html.ActionLink("Cursos", "Contact", "Home")
                                </li>
                                <li>
                                    @Html.ActionLink("Conferencias", "Contact", "Home")
                                </li>
                                <li>
                                    @Html.ActionLink("Visitas Academicas", "Contact", "Home")
                                </li>

                            </ul>
                        </li>
                        <li>@Html.ActionLink("¿Contactenos", "Contact", "Home")</li>

                        <li>@Html.ActionLink("Admin Noticias", "Index", "Noticia")</li>

                        <li>@Html.ActionLink("Admin Eventos", "Index", "Evento")</li>

                        <li>@Html.ActionLink("Tipos de Servicios", "Index", "Servicio")</li>

                    </ul>


                </div><!-- /.navbar-collapse -->
            </div><!-- /.container-fluid -->
        </nav>
    </header>

    <div id="body">
        @RenderSection("featured", required: false)
        <section class="content-wrapper main-content clear-fix" style="margin: 30px;">
            @RenderBody()
        </section>
    </div>





    <footer>
        <nav class="navbar navbar-default navbar-fixed-bottom" style="min-height:20px;">
            <div class="container">
                <label>Aplicacion Para el Cecep. By: J.C.R.Z. 2015</label>
            </div>
        </nav>
    </footer>

    @RenderSection("scripts", required: false)

</body>
</html>